WebSocketConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
        KeySchema:
            - AttributeName: connectionId
              KeyType: HASH
        AttributeDefinitions:
            - AttributeName: documentId
              AttributeType: S
            - AttributeName: connectionId
              AttributeType: S
            - AttributeName: userId
              AttributeType: S
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
            - IndexName: documentId-connectionId-index # FIRST GSI
              KeySchema:
                  - AttributeName: documentId
                    KeyType: HASH
                  - AttributeName: connectionId
                    KeyType: RANGE
              Projection:
                  ProjectionType: ALL
              ProvisionedThroughput:
                  ReadCapacityUnits: 1
                  WriteCapacityUnits: 1
            - IndexName: userId-index # SECOND GSI
              KeySchema:
                  - AttributeName: userId
                    KeyType: HASH
              Projection:
                  ProjectionType: ALL
              ProvisionedThroughput:
                  ReadCapacityUnits: 1
                  WriteCapacityUnits: 1

DocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
        AttributeDefinitions:
            - AttributeName: documentId
              AttributeType: S
        KeySchema:
            - AttributeName: documentId
              KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

UserDocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
        AttributeDefinitions:
            - AttributeName: userId
              AttributeType: S
            - AttributeName: documentId
              AttributeType: S
            - AttributeName: lastAccessedAt
              AttributeType: S
        KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: documentId
              KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
            - IndexName: userId-lastAccessedAt-index
              KeySchema:
                  - AttributeName: userId
                    KeyType: HASH
                  - AttributeName: lastAccessedAt
                    KeyType: RANGE
              Projection:
                  ProjectionType: ALL
              ProvisionedThroughput:
                  ReadCapacityUnits: 1
                  WriteCapacityUnits: 1
            - IndexName: documentId-index
              KeySchema:
                  - AttributeName: documentId
                    KeyType: HASH
                  - AttributeName: userId
                    KeyType: RANGE
              Projection:
                  ProjectionType: KEYS_ONLY
              ProvisionedThroughput:
                  ReadCapacityUnits: 1
                  WriteCapacityUnits: 1
