service: QuillStream-serverless
frameworkVersion: "3"

useDotenv: true

provider:
    name: aws
    runtime: nodejs20.x
    region: us-west-1

environment:
    WSSAPIGATEWAYENDPOINT:
        Fn::Join:
            - ""
            - - Ref: WebsocketsApi
              - ".execute-api"
              - Ref: AWS::Region
              - ".amazonaws.com/${sls:stage}"

package:
    individually: true

functions: ${file(./serverless-functions.yml)}

plugins:
    - serverless-esbuild
    - serverless-iam-roles-per-function
    - serverless-dotenv-plugin

custom:
    esbuild:
        packager: pnpm
        bundle: true
        minify: true
        keepNames: true
    dotenv:
        exclude:
            - ISSUER_URL
            - AUDIENCE
        required:
            file: true
